# -*- coding: utf-8 -*-
"""ANN_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8G5IaFcbq2MrvCVy6lM7fMkEfY_Hua0
"""

import numpy as np
import pandas as pd

data=pd.read_csv("/content/fraud_transactions_synthetic.csv")

data.head()

data.shape

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

x=data.drop(['is_fraud'],axis=1)
y=data['is_fraud']

x.head()

y.head()

from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test)=train_test_split(x,y,test_size=0.25)

x_train.shape[1]

model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name="input_layer"),
    layers.Dense(16,activation='relu',name='hidden_layer_1'),
    layers.Dense(32,activation='relu',name='hidden_layer_2'),
    layers.Dense(16,activation='tanh',name='hidden_layer_3'),
    layers.Dense(1,activation='sigmoid',name='output_layer')

])

model.compile(
    optimizer ='adam',
    loss='binary_crossentropy',
     metrics =['accuracy']

)

model.fit(x_train,y_train,epochs=20,batch_size=32)

pred=model.predict(x_test)

print(pred)