# -*- coding: utf-8 -*-
"""Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2pKZ1WBQob3U3B40FP17dlwSjcsPOf_
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import fashion_mnist

from google.colab import files
from PIL import Image

#Load the Fashion-MNIST dataset using TensorFlow/Keras.
(x_train,y_train),(x_test,y_test)=fashion_mnist.load_data()

#Number of training images
x_train.shape[0]

#Number of testing images
x_test.shape[0]

#Image dimensions
x_train.shape[1],x_train.shape[2]

#Normalize the image pixel values.
x_train_norm=x_train.astype('float32')/255.0
x_test_norm=x_test.astype('float32')/255.0

#Reshape the images to make them compatible with CNN layers
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

#Display at least five sample images along with their class labels.

plt.figure(figsize=(10,10))
for i in range(5):
    plt.subplot(1,5,i+1)
    plt.imshow(x_train[i], cmap='gray')
    plt.title(f"Label: {y_train[i]}")
plt.show()

#Create a Convolutional Neural Network using TensorFlow/Keras.
model = models.Sequential([
    layers.Input(shape=(28, 28, 1), name="input_layer"),
    layers.Conv2D(filters=16,kernel_size=(3,3),activation='relu',name="conv_layer_1"),
    layers.MaxPool2D(pool_size=(2,2),name="max_pool_1"),
    layers.Conv2D( filters=32,kernel_size=(3,3),activation='relu',name="conv_layer_2"),
    layers.MaxPool2D(pool_size=(2,2),name="max_pool_2"),
    layers.Flatten(name="flatten_layer"),
    layers.Dense(units=64,activation='relu',name="hidden_layer_1"),
    layers.Dense(units=32,activation='relu',name="hidden_layer_2" ),
    layers.Dense(units=10,activation='softmax',name="output_layer")
])

#Compile the model
model.compile(
    optimizer = 'adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

#part3
history = model.fit(x_train_norm,y_train,epochs=20,batch_size=32)

print("Number of Epochs:20", )
print("Batch Size: 32")
print("Final Training Accuracy:",history.history['accuracy'][-1])

predictions = model.predict(x_test_norm)

predicted_labels = np.argmax(predictions, axis=1)

print("Predicted Class Labels for First 10 Test Images:\n")

import matplotlib.pyplot as plt

plt.figure(figsize=(10,10))

for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(x_test[i].reshape(28,28), cmap='gray')
    plt.title(f"Actual: {y_test[i]}\nPred: {predicted_labels[i]}")
    plt.axis('off')

plt.tight_layout()
plt.show()

test_loss , test_accuracy = model.evaluate(x_test,y_test)
print('Test Accuracy:',test_accuracy)
print('Test loss:',test_loss)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predicted_labels)
print("confusion metrics\n",cm)

from sklearn.metrics import classification_report
print("Classification Report:\n")

print(classification_report(
    y_test,
    predicted_labels
))

"""1. Why are CNNs more suitable than Artificial Neural Networks (ANNs) for image classification?

CNNs are more suitable for image classification because they automatically learn important features such as edges, shapes, and textures from images. They preserve the spatial relationships between pixels and use fewer parameters than ANNs, making them more efficient and accurate for image data.

2. What is the purpose of a Convolution layer?

The Convolution layer extracts important features from the input image by applying filters (kernels). It detects patterns such as edges, corners, and textures, which help the model recognize different objects in the image.

3. Why is Max Pooling used in CNNs?

Max Pooling reduces the size of the feature maps while keeping the most important information. This decreases computation, reduces overfitting, and makes the model faster and more efficient.

4. Why is the Flatten layer required before the Dense layers?

The Flatten layer converts the two-dimensional feature maps into a one-dimensional vector. This allows the Dense layers to process the extracted features and perform the final classification.

5. Why is the Softmax activation function used in the output layer?

The Softmax activation function converts the output values into probabilities that sum to 1. The class with the highest probability is selected as the predicted class, making it suitable for multi-class classification problems like Fashion-MNIST.

6. How does the Adam optimizer help in training the CNN?

The Adam optimizer updates the model's weights efficiently by using adaptive learning rates and momentum. It speeds up convergence, improves training performance, and often achieves higher accuracy with less manual tuning than traditional optimization methods.
"""